name: 'Build & Deploy'

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
      with:
        submodules: true

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.6.0
      with:
        hugo-version: '0.110.0'
        extended: true

    - name: Build
      run: npm i && HUGO_ENVIRONMENT=production hugo --gc -s thesharptraveler.com

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.9.2
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./thesharptraveler.com/public
        cname: thesharptraveler.com
