name: 'Build & Deploy'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.6.0
      with:
        hugo-version: '0.110.0'
        extended: true

    - name: Build
      working-directory: ./thesharptraveler.com
      run: hugo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.9.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./thesharptraveler.com/public
        cname: thesharptraveler.com
